version: '3.7'
services:
  captain-template:
    build:
      context: captain
      target: develop-stage
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DNS_PROVIDER=${DNS_PROVIDER}
      - DEFAULT_HEALTHY_INTERVAL=${DEFAULT_HEALTHY_INTERVAL}
      - DEFAULT_UNHEALTHY_INTERVAL=${DEFAULT_UNHEALTHY_INTERVAL}
      - DEFAULT_FALL=${DEFAULT_FALL}
      - DEFAULT_RISE=${DEFAULT_RISE}
      - DEFAULT_CONNECT_TIMEOUT=${DEFAULT_CONNECT_TIMEOUT}
      - DEFAULT_READ_TIMEOUT=${DEFAULT_READ_TIMEOUT}
      - DEFAULT_COOL_DOWN=${DEFAULT_COOL_DOWN}
      - MEMBER_URLS=${MEMBER_URLS}
      - CAPTAIN_PORT=${CAPTAIN_PORT}
      - CAPTAIN_SECRET_KEY=${CAPTAIN_SECRET_KEY}
      - MATE_PORT=${MATE_PORT}
      - MATE_SECRET_KEY=${MATE_SECRET_KEY}
      - CONSUL_HTTP_TOKEN=${CONSUL_HTTP_TOKEN}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - TECHNITIUM_BASE_URL=${TECHNITIUM_BASE_URL}
      - TECHNITIUM_CUSTOM_ZONE_NAME=${TECHNITIUM_CUSTOM_ZONE_NAME}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DATADOG_SITE=${DATADOG_SITE}
      - NOTIFICATION_URL=${NOTIFICATION_URL}
      - NOTIFICATION_HEADER=${NOTIFICATION_HEADER}
    volumes:
      - ./captain:/app
      - ./__simulation__/data:/data
      - /app/dist
      - ./__simulation__/real-consul-app/certs/:/consul/config/certs/:ro
    entrypoint: ['sh', '-c']
    # command: ['exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']
    # command: ['pnpm i --config.confirmModulesPurge=false && exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']
    command:
      - |
        run-consul.sh
        exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234

  mate-template:
    build:
      context: mate
      target: develop-stage
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEEP_ALIVE=${__MATE__KEEP_ALIVE}
      - INTERVAL=${__MATE__INTERVAL}
      - CAPTAIN_SECRET_KEY=${__MATE__CAPTAIN_SECRET_KEY}
    volumes:
      - ./mate:/app
      - ./__simulation__/data:/data
      - /app/dist
    entrypoint: ['sh', '-c']
    # command: ['pnpm i --config.confirmModulesPurge=false && exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']
    command: ['exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']

  dummy-apps:
    build:
      context: ./__simulation__/dummy-apps
    volumes:
      - ./__simulation__/dummy-apps:/app
      - /app/dist
    environment:
      - NODE_ENV=${NODE_ENV}
    entrypoint: ['sh', '-c']
    cap_add:
      - NET_ADMIN
    # command: ['pnpm i --config.confirmModulesPurge=false && exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']
    command: ['exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']  

  # https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml
  dns-server-template:
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - '5380:5380/tcp' #DNS web console (HTTP)
      - '53:53/udp' #DNS service
      - '53:53/tcp' #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD=admin #DNS web console admin user password.
      - DNS_SERVER_FORWARDERS=8.8.8.8, 8.8.4.4 #Comma separated list of forwarder addresses.
    # volumes:
    #   - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
