version: '3.7'
services:
  captain-template:
    build:
      context: .
      target: develop-stage
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DNS_PROVIDER=${DNS_PROVIDER}
      - DEFAULT_HEALTHY_INTERVAL=${DEFAULT_HEALTHY_INTERVAL}
      - DEFAULT_UNHEALTHY_INTERVAL=${DEFAULT_UNHEALTHY_INTERVAL}
      - DEFAULT_FALL=${DEFAULT_FALL}
      - DEFAULT_RISE=${DEFAULT_RISE}
      - DEFAULT_CONNECT_TIMEOUT=${DEFAULT_CONNECT_TIMEOUT}
      - DEFAULT_READ_TIMEOUT=${DEFAULT_READ_TIMEOUT}
      - DEFAULT_COOL_DOWN=${DEFAULT_COOL_DOWN}
      - MEMBER_URLS=${MEMBER_URLS}
      - CAPTAIN_PORT=${CAPTAIN_PORT}
      - CAPTAIN_SECRET_KEY=${CAPTAIN_SECRET_KEY}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
    volumes:
      - .:/app
      - ./__simulation__/data:/data
      - /app/dist
      - /app/.pnpm-store
      - /app/node_modules
    entrypoint: ['sh', '-c']
    # command: ['exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']
    command: ['pnpm i --config.confirmModulesPurge=false && exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']

  web-app-template:
    build:
      context: ./__simulation__/web-app
      target: develop-stage
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./__simulation__/web-app:/app
      - /app/dist
      - /app/.pnpm-store
      - /app/node_modules
    entrypoint: ['sh', '-c']
    command: ['pnpm i --config.confirmModulesPurge=false && exec nodemon --signal SIGTERM -- --inspect=0.0.0.0:9234']

  # https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml
  dns-server-template:
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - '5380:5380/tcp' #DNS web console (HTTP)
      - '53:53/udp' #DNS service
      - '53:53/tcp' #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD=admin #DNS web console admin user password.
      - DNS_SERVER_FORWARDERS=8.8.8.8, 8.8.4.4 #Comma separated list of forwarder addresses.
    # volumes:
    #   - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
