version: '3.7'
services:

  # https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml
  dns-server:
    extends:
      file: docker-compose-base.yml
      service: dns-server-template
    networks:
      custom-network:
        ipv4_address: 10.6.0.2
    
  captain-test-main:
    extends:
      file: docker-compose-base.yml
      service: captain-template
    environment:
      - NODE_ENV=test
      - CONSUL_HTTP_ADDR=http://dummy-consul-apps/consul-1
      - MEMBER_URLS=ws://127.0.0.1:7401,ws://127.0.0.1:7402,ws://127.0.0.1:7403
      - SELF_URL=ws://127.0.0.1:7401
      - CAPTAIN_PORT=7401
      - CAPTAIN_SECRET_KEY=erwoc2q34m23nlfWS69ri
      - DNS_PROVIDER=technitium
      - TECHNITIUM_BASE_URL=http://10.6.0.2:5380
      - TECHNITIUM_CUSTOM_ZONE_NAME=ops
      - SLACK_TOKEN=dummy-slack-token
      - SLACK_CHANNEL_ID=dummy-slack-channel-id
      - DATADOG_SITE=http://dummy-datadog-site
      - DATADOG_API_KEY=dummy-datadog-api-key
      - NOTIFICATION_URL=http://dummy-generic-notification-url
      - NOTIFICATION_HEADER={"notify_token":"dummy-sample-token-value"}
      - WEBSERVICE_YAML_LOCATION=./__tests__/data/captain-one-services.yaml
      - MATE_PORT=7450
      # - DEBUG=captain
      # common to both captain and mate
      - MATE_SECRET_KEY=ksjdhf2q34m23nlfWS69ri
      # mate properties
      - CAPTAIN_URL=ws://127.0.0.1:7450
      - __MATE_TEST_1__WEBSERVICE_YAML_LOCATION=./__tests__/data/mate-1-services.yaml
      - __MATE_TEST_2__WEBSERVICE_YAML_LOCATION=./__tests__/data/mate-2-services.yaml

    volumes:
      - /app/.pnpm-store
      - /app/node_modules
    networks:
      custom-network:
        ipv4_address: 10.6.0.11
    ports: 
      - 8001:80
    depends_on:
      - dns-server
    # dns:
    #   - 10.6.0.2
    #   - 8.8.4.4
    command: ['pnpm i --config.confirmModulesPurge=false && exec pnpm run jest-exec']
    # command: ['pnpm i --config.confirmModulesPurge=false && sleep infinity']
    # command: ['pnpm i --config.confirmModulesPurge=false && exec pnpm exec -- jest --forceExit --detectOpenHandles --coverage']
networks:
  custom-network:
    name: ${COMPOSE_PROJECT_NAME}-captain-test-network
    driver: bridge
    # disable ipv6 to simplify network setup
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
