version: '3.7'
services:
  captain-1:
    extends: 
      file: docker-compose-base.yml
      service: captain-template
    environment:
      - SELF_URL=ws://10.5.0.11:7400
      - DEBUG=true
    networks:
      custom-network:
        ipv4_address: 10.5.0.11
    ports: 
      - 8001:80
    dns:
      - 10.5.0.2
      - 8.8.4.4      
  captain-2:
    extends: 
      file: docker-compose-base.yml
      service: captain-template
    environment:
      - SELF_URL=ws://10.5.0.12:7400
    networks:
      custom-network:
        ipv4_address: 10.5.0.12
    ports: 
      - 8002:80
    dns:
      - 10.5.0.2
      - 8.8.4.4      
  captain-3:
    extends: 
      file: docker-compose-base.yml
      service: captain-template
    environment:
      - SELF_URL=ws://10.5.0.13:7400
    networks:
      custom-network:
        ipv4_address: 10.5.0.13
    ports: 
      - 8003:80
    dns:
      - 10.5.0.2
      - 8.8.4.4
  crm-app-1:
    extends:
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.21
  crm-app-2:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.22
  crm-app-3:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.23
  ecommerce-app-1:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.31
  ecommerce-app-2:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.32
  ecommerce-app-3:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.33
  ecommerce-app-4:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.34
  helpdesk-app-1:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.41
  helpdesk-app-2:
    extends: 
      file: docker-compose-base.yml
      service: web-app-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.42

  # https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml
  dns-server:
    extends:
      file: docker-compose-base.yml
      service: dns-server-template
    networks:
      custom-network:
        ipv4_address: 10.5.0.2

networks:
  custom-network:
    driver: bridge
    # disable ipv6 to simplify network setup
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

