---
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:import/recommended
  - plugin:promise/recommended
  - standard
  # moved prettier to last so it overrides in case of conflict between eslint and prettier
  - prettier  
plugins:
  - node
  - prettier  
  - standard
  - import
  - promise
rules:
  node/no-deprecated-api: off
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  prefer-const: off
  # space-before-function-paren: ["error", {
  #   "anonymous": "ignore",
  #   "named": "ignore",
  #   "asyncArrow": "ignore"
  # }]
  no-process-exit: "off"
  node/no-unsupported-features/es-syntax:
    - error
    - ignores: ['modules']
env:
  node: true
  es2021: true
parserOptions:
  ecmaVersion: 12
  allowImportExportEverywhere: true
