---
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:promise/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - "plugin:@typescript-eslint/recommended"
  - standard
  - prettier  
plugins:
  - node
  - prettier  
  - standard
  - import
  - promise
  - "@typescript-eslint"
rules:
  node/no-missing-import: off # .js import from typescript files
  "@typescript-eslint/no-explicit-any": off # support using explicit 'any'
  node/no-deprecated-api: off
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  prefer-const: off
  # space-before-function-paren: ["error", {
  #   "anonymous": "ignore",
  #   "named": "ignore",
  #   "asyncArrow": "ignore"
  # }]
  no-process-exit: "off"
  node/no-unsupported-features/es-syntax:
    - error
    - ignores: ['modules']
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
overrides:
  # 'no-undef' not recomended for typescript
  - files: ['*.ts']
    rules:
      'no-undef': 'off'
  # test files specific rules
  - files: ['__tests__/**/*.ts', 'jest.config.ts']
    rules:
      'node/no-unpublished-import': "off"
env:
  node: true
  es2021: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  allowImportExportEverywhere: true
settings:
  import/resolver:
    typescript: {}