version: '3.7'

services:

  captain-1:
    image: hashicorp/consul:1.11.2
    container_name: captain-1
    restart: always
    volumes:
     - ./server1.json:/consul/config/server1.json
     - ./certs/:/consul/config/certs/
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  captain-2:
    image: hashicorp/consul:1.11.2
    container_name: captain-2
    restart: always
    volumes:
     - ./server2.json:/consul/config/server2.json
     - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  captain-3:
    image: hashicorp/consul:1.11.2
    container_name: captain-3
    restart: always
    volumes:
     - ./server3.json:/consul/config/server3.json
     - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json
     - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent"

networks:
  consul:
    driver: bridge

